title: 技术探索与分享
description: Android开发、嵌入式Linux和MCU的学习笔记
author: Your Name
theme: jekyll-theme-minimal

# 分类设置
categories: 
  - Android
  - 嵌入式Linux
  - MCU

# 导航设置
navigation:
  - title: 首页
    url: /
  - title: 分类
    url: /categories
  - title: 关于
    url: /about 