title: 技术探索与分享
description: Android开发、嵌入式Linux和MCU的学习笔记
author: Your Name
theme: jekyll-theme-minimal

# 分类设置
categories: 
  - Android
  - 嵌入式Linux
  - MCU

# 导航设置
navigation:
  - title: 首页
    url: /
  - title: 分类
    url: /categories
  - title: 关于
    url: /about 

/* 添加渐变背景 */
body {
  background: linear-gradient(120deg, #fdfbfb 0%, #ebedee 100%);
}

/* 为标题添加动画效果 */
h1 {
  animation: fadeIn 2s ease-in;
}

/* 卡片式设计 */
.content {
  background: white;
  border-radius: 8px;
  box-shadow: 0 2px 15px rgba(0,0,0,0.1);
  padding: 20px;
  margin: 20px;
}

/* 响应式布局 */
@media (max-width: 768px) {
  .container {
    width: 95%;
    padding: 10px;
  }
} 