title: 技术探索与分享
description: Android开发、嵌入式Linux和MCU的学习笔记
author: Your Name
theme: jekyll-theme-minimal

# Markdown 配置
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# 构建配置
permalink: /:categories/:title/
paginate: 5
paginate_path: "/page:num/"

# 分类设置
categories: 
  - Android
  - 嵌入式Linux
  - MCU

# 导航设置
navigation:
  - title: 首页
    url: /
  - title: 分类
    url: /categories
  - title: 关于
    url: /about 