title: 技术博客
description: Android开发、嵌入式Linux和MCU的学习笔记
author: Your Name
theme: jekyll-theme-minimal

# Markdown 配置
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: prismjs
  syntax_highlighter_opts:
    block:
      line_numbers: false
      wrap: true
      inline: false

# 构建配置
permalink: /:categories/:title/
paginate: 5
paginate_path: "/page:num/"

# 分类设置
categories: 
  - Android
  - 嵌入式Linux
  - MCU

# 文章集合配置
collections:
  posts:
    output: true
    permalink: /:collection/:path/

# 文章路径设置
include:
  - posts

# 导航设置
navigation:
  - title: 首页
    url: /
  - title: 分类
    url: /categories
  - title: 搜索
    url: /search
  - title: 关于
    url: /about 